[project]
name = "goodenough"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "autodistill>=0.1.29",
    "autodistill-clip>=0.1.5",
    "autodistill-grounding-dino>=0.1.4",
    "autodistill-yolov11>=0.1.4",
    "bs4>=0.0.2",
    "openai-clip>=1.0.1",
    "requests>=2.32.3",
    "roboflow>=1.1.62",
    "scikit-learn>=1.6.1",
    "supervision>=0.24.0",
    "torch>=2.7.0",
]
